apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: rabbitmq
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/rabbitmq
    version: CHART_VERSION
