apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: horizon
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/horizon
    version: "0.3.0"
