apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: freezer
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/freezer
    version: "0.2.0"
