apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: glance
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/glance
    version: CHART_VERSION
