apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: octavia
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/octavia
    version: CHART_VERSION
